---
name: "jellyfin-plugin-mergeVersions"
guid: "bc4aad2e-d3d0-4725-a5e2-fd07949e5b42"
version: "5" # Please increment with each pull request
jellyfin_version: "10.7.0" # The earliest binary-compatible version
owner: "jellyfin"
nicename: "Merge Versions"
description: "Jellyfin Merge Versions plugin is a plugin that automatically groups every repeated movie;"
overview: "Jellyfin Merge Versions plugin is a plugin that automatically groups every repeated movie;"
category: "General"
artifacts:
  - "Jellyfin.Plugin.MergeVersions.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net5.0"
